#!/usr/bin/env python3
"""Ignore-patterns test: vendored/generated files must be skipped, and the
skips must be reported — never silent.

Proves the done-when for "Ignore patterns for generated/vendored files":
  1. a diff touching vendor/ yields zero findings and names the skipped file
  2. default fnmatch patterns catch node_modules, *.min.js, lockfiles,
     protobuf stubs at any nesting depth
  3. a .pr-review.yaml `ignore:` list replaces the defaults
  4. generated-code markers (@generated, "DO NOT EDIT") skip the file even
     when its path matches no pattern
  5. CLI --ignore-pattern layers on top of the defaults
  6. the markdown report says how many files were skipped

Run:  python3 test_ignore.py
"""

import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from reviewer.comments import findings_to_markdown  # noqa: E402
from reviewer.ignore import (  # noqa: E402
    DEFAULT_IGNORE_PATTERNS, effective_patterns, is_ignored,
    looks_generated, path_matches)
from reviewer.repo_config import parse_config_text  # noqa: E402
from reviewer.reviewer import Reviewer  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))

passed = failed = 0


def check(name, cond):
    global passed, failed
    if cond:
        passed += 1
        print(f"  ok  {name}")
    else:
        failed += 1
        print(f"  FAIL {name}")


def vendor_diff(path="vendor/jquery.min.js"):
    # content that would absolutely get flagged if it were reviewed:
    # an AWS key (secrets), a print (debug_leftovers), a TODO (todos)
    return (
        f"diff --git a/{path} b/{path}\n"
        f"--- /dev/null\n+++ b/{path}\n"
        "@@ -0,0 +1,4 @@\n"
        '+aws_key = "AKIAIOSFODNN7EXAMPLE"\n'
        '+print("debug")\n'
        "+# TODO: minify better\n"
        "+var x = 1;\n"
    )


print("== done-when: a vendor/ diff produces no findings, skips reported ==")
findings, skipped = Reviewer().review_and_log(vendor_diff())
check("vendor/ diff yields zero findings", findings == [])
check("vendor/ file is named in the skipped list",
      skipped == ["vendor/jquery.min.js"])
md = findings_to_markdown(findings, skipped)
check("markdown says files were skipped",
      "Skipped 1 generated/vendored file" in md
      and "vendor/jquery.min.js" in md)

print("== default fnmatch patterns ==")
for p in ["node_modules/react/index.js", "static/app.min.js",
          "package-lock.json", "api/stub_pb2.py", "dist/bundle.js",
          "vendor/a/b/deep.js"]:
    check(f"default patterns ignore {p}",
          path_matches(p, DEFAULT_IGNORE_PATTERNS))
check("plain source files are not ignored",
      not path_matches("reviewer/checks.py", DEFAULT_IGNORE_PATTERNS))

print("== generated-code markers ==")
check("@generated marker detected",
      looks_generated(["// @generated by protoc", "package foo;"]))
check("DO NOT EDIT marker detected",
      looks_generated(["# Code generated by Django. DO NOT EDIT."]))
check("ordinary code is not flagged as generated",
      not looks_generated(["def foo():", "    return 1"]))
gen_diff = ("diff --git a/gen/client.py b/gen/client.py\n"
            "--- /dev/null\n+++ b/gen/client.py\n"
            "@@ -0,0 +1,2 @@\n"
            "+# Code generated by protoc. DO NOT EDIT.\n"
            '+aws_key = "AKIAIOSFODNN7EXAMPLE"\n')
findings, skipped = Reviewer().review_and_log(gen_diff)
check("marked-generated file skipped despite the planted secret",
      findings == [] and skipped == ["gen/client.py"])

print("== .pr-review.yaml ignore: replaces the defaults ==")
cfg = parse_config_text("ignore:\n  - docs/*\n")
check("custom ignore list parsed", cfg.ignore_patterns == ["docs/*"])
check("custom list no longer ignores vendor/",
      effective_patterns(cfg.ignore_patterns) == ["docs/*"])
findings, skipped = Reviewer(config=cfg).review_and_log(vendor_diff())
check("vendor/ is reviewed again under a custom list "
      "(planted secret surfaces)", len(findings) > 0 and skipped == [])
findings, skipped = Reviewer(config=cfg).review_and_log(
    vendor_diff("docs/guide.md"))
check("custom pattern docs/* skips the docs file",
      findings == [] and skipped == ["docs/guide.md"])
cfg2 = parse_config_text("ignore:\n")
check("explicit empty ignore: disables ignoring",
      cfg2.ignore_patterns == [] and effective_patterns([]) == [])

print("== CLI --ignore-pattern layers on top of defaults ==")
proc = subprocess.run(
    [sys.executable, os.path.join(HERE, "cli.py"),
     "--diff", os.path.join(HERE, "evals", "sample_pr.diff"),
     "--ignore-pattern", "payments.py", "--ignore-pattern", "README.md"],
    capture_output=True, text=True, cwd=HERE)
check("cli flag runs clean", proc.returncode == 0)
check("cli reports the extra skips",
      "Skipped 2 generated/vendored files" in proc.stdout
      and "payments.py" in proc.stdout)

print(f"\n{passed} passed, {failed} failed")
sys.exit(1 if failed else 0)
