"""Ignore patterns for vendored and generated files.

Nobody wants a review comment on a minified jquery bundle or a
protoc-generated stub — the signal is zero and the noise is real. This
module decides which files in a diff get reviewed and which are skipped.

Two mechanisms:

1. Path patterns (fnmatch style): "vendor/*", "*.min.js", "package-lock.json"…
   Defaults below cover the usual suspects; a repo overrides them with an
   `ignore:` list in .pr-review.yaml (see reviewer/repo_config.py).

2. Generated-code markers: files whose added lines carry the standard
   "this file is machine-written" markers (@generated, "Code generated …",
   "DO NOT EDIT") are skipped regardless of their path — generated code
   has a generator that deserves the review, not the output.
"""

from __future__ import annotations

import fnmatch

# the usual suspects — third-party bundles, build output, lockfiles and
# machine-written stubs. reviewed repos can replace this whole list via
# .pr-review.yaml; the CLI --ignore-pattern flag adds to it.
DEFAULT_IGNORE_PATTERNS = [
    # vendored third-party code — review the dependency pin, not the bundle
    "vendor/*", "third_party/*", "third-party/*", "node_modules/*",
    # build output that somehow landed in the diff
    "dist/*", "build/*", "out/*",
    # minified bundles
    "*.min.js", "*.min.css",
    # lockfiles — machine-written dependency pins, huge and boring
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
    "poetry.lock", "Pipfile.lock", "Cargo.lock", "Gemfile.lock",
    "*.lock",
    # generated protocol buffers and other machine-written stubs
    "*.pb.go", "*_pb2.py", "*_pb2_grpc.py", "*.pb.js", "*.pb.ts",
    "*.generated.*", "*.g.cs",
]

# markers machine generators leave at the top of their output —
# matched case-insensitively against the added lines of each file
_GENERATED_MARKERS = (
    "@generated",
    "code generated",
    "do not edit",
    "auto-generated",
    "generated by",
)

# only the first few dozen added lines get scanned — the markers live at
# the top of generated files, no point reading a 10k-line bundle for them
_MARKER_SCAN_LINES = 40


def looks_generated(added_lines: list[str]) -> bool:
    """True when the added lines carry a standard generated-code marker."""
    for line in added_lines[:_MARKER_SCAN_LINES]:
        lowered = line.lower()
        if any(m in lowered for m in _GENERATED_MARKERS):
            return True
    return False


def path_matches(path: str, patterns: list[str]) -> bool:
    # fnmatch's * crosses / so "vendor/*" catches vendor/a/b.js too
    return any(fnmatch.fnmatch(path, p) for p in patterns)


def is_ignored(file_diff, patterns: list[str]) -> bool:
    """Should this file be skipped by the review pipeline?"""
    if path_matches(file_diff.path, patterns):
        return True
    # generated markers are content-based, so they apply even when the
    # repo replaced the default pattern list with its own
    if looks_generated([h.text for h in file_diff.added_lines]):
        return True
    return False


def effective_patterns(ignore_patterns: list[str] | None) -> list[str]:
    # None = no config given -> the built-in defaults; an explicit (even
    # empty) list from the repo's config wins over the defaults
    return DEFAULT_IGNORE_PATTERNS if ignore_patterns is None \
        else list(ignore_patterns)
